### ISSUE TITLE
Question about reconcilePCIDeviceClaims

### ISSUE THREAD

**Issue by w13915984028** [harvester/pcidevices#17]
Question about reconcilePCIDeviceClaims:

1. The following `Update` operations,  do not use a copied object, but the local queried one
```
				_, err = h.pdcClient.Update(&pdc)
				if err != nil {
					return err
				}
				_, err = h.pdcClient.UpdateStatus(&pdc)
				if err != nil {
					return err
				}
```

2. The `pdc` spec seems not changed in `reconcilePCIDeviceClaims`, but here it calls `Update` and `UpdateStatus`, is one time of `Update*` is enough?

3. Should `if pdc.DeletionTimestamp != nil` be checked before `if !pdc.Status.PassthroughEnabled` ?

4. Those change of `pdc.Status.PassthroughEnabled` but `return err`, may cause (k8s) controller local cached data is not consistant with apiserver.

```
						if err != nil {
							pdc.Status.PassthroughEnabled = false
							return err
						}
```

**Comment by tlehman** [comment]
For 1, there is no deepCopy on the pdc runtime.Object, can you clarify?
For 4, I'm not sure I understand, is the problem that a status change without a call to UpdateStatus will cause cache invalidation? If so I can fix that.


For 3, I pushed that correction, we should be checking the deletion time, nice catch.

For 2, I remember when I was first developing this, the call to Update alone was not enough. There's no metadata change so I will see if just removing the call to Update and keeping UpdateStatus works.

**Comment by tlehman** [comment]
To answer 2, I removed the call to `Update` before `UpdateStatus`, and the PCI Devices were all created and maintained correctly. Here is the commit: https://github.com/harvester/pcidevices/pull/14/commits/41ca67a10aae242bbd501f26168c4e4675801618

**Comment by w13915984028** [comment]
An example about how to update k8s object:

It is always necessary to `deep copy an object out`, and  `set the desired value`, then check `reflect.DeepEqual`,  finally call `client.Update`

harvester/pkg/controller/backup/backup_status.go

```
func (h *Handler) updateConditions(vmBackup *harvesterv1.VirtualMachineBackup) error {
	var vmBackupCpy = vmBackup.DeepCopy()
	....
	vmBackupCpy.Status.ReadyToUse = pointer.BoolPtr(ready)

	if !reflect.DeepEqual(vmBackup.Status, vmBackupCpy.Status) {
		if _, err := h.vmBackups.Update(vmBackupCpy); err != nil {
			return err
		}
	}
	return nil
}	
```


Do NOT use the `queried object`  (e.g.  List())  to do `local change` and `client.Update()` directly.

**Comment by tlehman** [comment]
I see, I'll make that change, thank you.

**Comment by w13915984028** [comment]
Also refer official guide:

https://github.com/kubernetes/sample-controller/blob/master/docs/images/client-go-controller-interaction.jpeg

https://github.com/kubernetes/sample-controller/blob/master/controller.go#L321
