### ISSUE TITLE
PDC controller is slow for user claim

### ISSUE THREAD

**Issue by w13915984028** [harvester/pcidevices#18]
PDC controller is slow for user claim, as it depends on a 20s timer.

A better solution is to work as normal controller, watch & react with PDC CRD object, meanwhile, use timer to enqueue self about routine reconciler.

**Comment by tlehman** [comment]
For Wrangler, would that be the `OnChange` event? I don't see an `OnCreate`

**Comment by w13915984028** [comment]
`OnCreate` is a special case of `OnChange`, it is not defined separately.

**Comment by tlehman** [comment]
Fixed in https://github.com/harvester/pcidevices/pull/15/commits/669d11c9b09a4cbb9fef6d54efe1f11b7d95f673
