### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by Lost135** [harvester/pcidevices#33]
How to use it with harvester?
I created the [crds.yaml](https://github.com/harvester/pcidevices/blob/master/charts/templates/crds.yaml) , PCIDevice and PCIDeviceClaim, what is the next?

Anyone can help?

**Comment by Lost135** [comment]
So it `s only deploy with harvester.iso ? When can it be installed with helm or other way？

**Comment by tlehman** [comment]
Great question! Sorry for the delay, currently it is designed to work with harvester, but you can build the helm chart: https://github.com/harvester/charts/tree/master/charts/harvester-pcidevices-controller

Let me know if you need any more help
